version: '3.7'

services:
  freshclam:
    build:
      context: scanner/clamav/docker
      dockerfile: Dockerfile
    environment:
      MODE: freshclam
    volumes:
    - conf:/etc/clamav
    - data:/var/lib/clamav        
    networks:
      virus-scanner-network:
        aliases:
          - virus-scanner-network
  
  clamav:
    depends_on:
      - freshclam
    build:
      context: scanner/clamav/docker
      dockerfile: Dockerfile
    environment:
      MODE: clamd
    ulimits:
      stack: 1048576
    volumes:
      - conf:/etc/clamav
      - data:/var/lib/clamav
    ports:
      - "3310:3310"

    expose:
      - 3310
    networks:
      virus-scanner-network:
        aliases:
          - virus-scanner-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - virus-scanner-network

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" # Default edge port
    environment:
      - SERVICES=s3
      - START_WEB=0
      - DEFAULT_REGION=us-east-1

  # api:
  #   restart: always
  #   build:
  #     context: verializer/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - clamav
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  #   env_file:
  #     - verializer/.env
  #   networks:
  #     virus-scanner-network:
  #       aliases:
  #         - virus-scanner-network

networks:
  virus-scanner-network:
    driver: bridge


volumes:
  conf:
  data:
  mongodb_data: